# do NOT remove the following line
from visualize.codify.SketchBasedFeat import *


def code2json(_code: str) -> dict:
    exec("InitSERPairs()")
    # WARNING: We do NOT check the **safety of the code** to be executed, please make sure the code does not contain any malicious code, otherwise it may cause security issues
    # If the code is generated by a model that you trained yourself, there are usually no security issues
    exec(_code)
    triples = globals().get("SER_PAIRS")
    json_data = {
        "features": {},
        "sequence": []
    }
    for SERPair in triples:
        for feat in SERPair.back2json():
            json_data["features"][feat["id"]] = feat
            json_data["sequence"].append({
                "index": None,
                "type": feat["type"],
                "name": feat["name"],
                "feature_id": feat["id"]
            })
    return json_data
